
#define ABOUT_LIZENZ	111

#define ALPHA_2D                        103
#define ALPHA_ENDE                      102
#define ALPHA_START                     101
#define ALPHA_WINKEL                    105

#define ANSICHT_DATEN                   110
#define ANSICHT_DRAFT                   204
#define ANSICHT_HINTEN                  111
#define ANSICHT_HOEHE_EDIT              210
#define ANSICHT_LINKS                   108
#define ANSICHT_MARK_LINKS              212
#define ANSICHT_MARK_RECHTS             113
#define ANSICHT_PLOTPOS                 222
#define ANSICHT_PREVIEW                 205
#define ANSICHT_RECHTS                  109
#define ANSICHT_SHOW1                   105
#define ANSICHT_SHOW2                   106
#define ANSICHT_SHOW3                   107
#define ANSICHT_SHOW4                   112
#define ANSICHT_VORNE                   206
#define ANSICHT_XYWINKEL                201
#define ANSICHT_XY_EDIT                 208
#define ANSICHT_ZEICHENSATZ             211
#define ANSICHT_ZW                      203
#define ANSICHT_ZWINKEL                 202
#define ANSICHT_Z_EDIT                  209

#define CAPTURE_BITMAP                  23
#define DLG_ERROR	772
#define DLG_LUMI	774
#define DLG_TOPO	771
#define DO_NO_OVERFLOW                  34

#define E_COM	61
#define E_DSP_DLL                       39
#define E_DSP_TARGET                    42
#define E_FILE                          25
#define E_FILE_CORRUPT                  35
#define E_HARDDISK                      38
#define E_IMPORT	37
#define E_LOCKIN                        43
#define E_LOW_MEMORY                    32
#define E_MEMORY                        3
#define E_NOT_FITTED                    33
#define E_NO_BITMAP                     24
#define E_TOO_SMALL                     36
#define E_UNKNOWN_FILE                  30

#define FARB_1                          102
#define FARB_2                          103
#define FARB_3                          104
#define FARB_3D                         112
#define FARB_KONT                       110
#define FARB_KONT_DIST                  111
#define FARB_KONT_EINHEIT               120
#define FARB_KONT_TOL                   114
#define FARB_MOD                        115
#define FARB_MOD_DIST                   116
#define FARB_MOD_EINHEIT                113
#define FARB_PREVIEW                    118
#define FARB_SHOW1                      105
#define FARB_SHOW2                      106
#define FARB_SHOW3                      107
#define FARB_SPEZ_Z                     122
#define FARB_SHOW_LUT	11
#define FARB_LOAD_LUT	10
#define FARB_LUT	101
#define FARB_START                      108
#define FARB_START_EINHEIT              124
#define FARB_START_ZAHL                 123
#define FARB_TITEL                      117
#define FARB_WECHSELE                   7979
#define FARB_WEITE                      109
#define FARB_WEITE_EINHEIT              126
#define FARB_WEITE_ZAHL                 125
#define FARB_Z_ACHSE                    119
#define FARB_Z_UNIT                     121

#define FFT_FKT	201
#define FFT_HIGH_FREQ	206
#define FFT_HIGH_FREQ_SL	207
#define FFT_HIGH_W	208
#define FFT_HIGH_W_SL	209
#define FFT_LOW_FREQ	202
#define FFT_LOW_FREQ_SL	203
#define FFT_LOW_W	204
#define FFT_LOW_W_SL	205

#define GLATT_PUNKTE                    101
#define GROSS_FAKTOR                    106
#define GROSS_FAKTOR_OK                 105
#define GROSS_H                         103
#define GROSS_W                         102
#define GROSS_X_Y                       104

#define HUB_AA	140
#define HUB_INFO                        108
#define HUB_KEINE	143
#define HUB_KOMM                        109
#define HUB_LADEN                       118
#define HUB_LUMI                        119
#define HUB_LUMI_UNIT                   114
#define HUB_MKM	142
#define HUB_NM	141
#define HUB_SHOW_OFF                    110
#define HUB_X                           101
#define HUB_X_OFF                       120
#define HUB_Y                           102
#define HUB_Y_OFF                       121
#define HUB_Z                           103
#define HUB_Z_UNIT                      112

#define IDD_ZAHL                        101

#define HILFETEXT                       7799
#define IDHELP                          9
#define MOVIE_SCALE_Z	828
#define MOVIE_SELECT	800
#define MOVIE_COMBOBOX_FRAME	801
#define MOVIE_PLAY	802
#define MOVIE_BACKGROUND	803
#define MOVIE_CHOOSE_BACKGROUND	804
#define MOVIE_YSIZE	805
#define MOVIE_XSIZE	806
#define MOVIE_FRAME_NO	807
#define MOVIE_TRANSITION	808
#define MOVIE_YOFFSET	809
#define MOVIE_FRAMESIZE_X	810
#define MOVIE_FRAMESIZE_Y	811
#define MOVIE_ZOFFSET	812
#define MOVIE_XOFFSET	813

#define IDM_1ZU1                        586
#define IDM_1ZU2                        587
#define IDM_1ZU3                        588
#define IDM_1ZU4                        589
#define IDM_2ZU1	590
#define IDM_3DANSICHT                   581
#define IDM_3DANSICHT_DEFAULT           579
#define IDM_3DMITTEL                    544
#define IDM_ABOUT                       610
#define IDM_ALPHA                       572
#define IDM_ARRANGE                     604
#define IDM_AUTOKORRELATION	555
#define IDM_BROWSE	596
#define IDM_CASCADE                     601
#define IDM_CLOSE                       521
#define IDM_CLOSEALL                    602
#define IDM_COPY                        532
#define IDM_COPY_MASKE                  561
#define IDM_COPY_SCANLINE               533
#define IDM_CUT	24322
#define IDM_DESPIKE                     547
#define IDM_DIFFERENTIAL                552
#define IDM_DIFF_NULL                   543
#define IDM_DREHEN                      540
#define IDM_DRUCKEN                     524
#define IDM_DRUCKEREINSTELLEN           523
#define IDM_EXIT                        999
#define IDM_EXPORT_ANSICHT              517
#define IDM_EXPORT_LUMI                 519
#define IDM_EXPORT_TOPO                 520
#define IDM_EXPORT_ASCII				518
#define IDM_EXPORT_DI                   54321
#define IDM_FALSCHFARBEN                580
#define IDM_FFT                         554
#define IDM_FFT_MITTEL                  546
#define IDM_FIT_TO_WINDOW               585
#define IDM_GLEITEND_MITTEL             545
#define IDM_GROESSE                     549
#define IDM_HILFEINHALT                 611
#define IDM_HILFESUCHEN                 612
#define IDM_HILFETUTOR                  613
#define IDM_HISTOGRAMM                  571
#define IDM_IMPORT_ASCII	514
#define IDM_IMPORT_BINAER	515
#define IDM_INTEGRAL                    553
#define IDM_INVERT_MASKE                560
#define IDM_KONTOUR                     574
#define IDM_DOT_MODE					673
#define IDM_DOTS_ADD					674
#define IDM_DOTS_REMOVE					675
#define IDM_DOTS_AUTO					676
#define IDM_DOTS_MARK					677
#define IDM_DOTS_CLEAR					678
#define IDM_DOTS_SAVE					679
#define IDM_LOESCHE_MASKE               562
#define IDM_MASKE_HORIZONTAL_MITTELN    563
#define IDM_MASKE_VERTIKAL_MITTELN      564
#define IDM_MASZE                       582
#define IDM_MATHE                       551
#define IDM_MEDIAN                      548
#define IDM_MESS                        512
#define IDM_MESS_APPROACH               223
#define IDM_MESS_ENDE			219
#define IDM_MESS_FREQ                   222
#define IDM_MESS_MESS                   225
#define IDM_MESS_PID                    224
#define IDM_MESS_SERIAL                 221
#define IDM_MESS_SPEICHERN		220
#define IDM_NEGATIV                     550
#define IDM_NULL                        542
#define IDM_NUR_ERROR                   536
#define IDM_NUR_LUMI                    538
#define IDM_NUR_TOPO                    535
#define IDM_TRACK_ALL					539
#define IDM_OPEN                        513
#define IDM_OPEN_FROM_STRING					  599
#define IDM_ORIENTIERUNG                573
#define IDM_PASTE                       534
#define IDM_PROFIL                      578
#define IDM_PROGRAMM	605
#define IDM_PROG_RUN	101
#define IDM_PROG_STOP	102
#define IDM_PROG_TRACE	1
#define IDM_MOVIE_MAKER									525
#define IDM_RECENT1                     526
#define IDM_RECENT2                     527
#define IDM_RECENT3                     528
#define IDM_RECENT4                     529
#define IDM_REDO                        531
#define IDM_REDRAW                      583
#define IDM_RMS                         570
#define IDM_SAVE                        516
#define IDM_SCANLINE                    575
#define IDM_SEITENLAYOUT                522
#define IDM_SHOW                        590
#define IDM_SHOW_ERROR                  592
#define IDM_SHOW_LUMI                   594
#define IDM_SHOW_TOPO                   591
#define IDM_TILE                        600
#define IDM_UMBENNEN                    603
#define IDM_UNDO                        530
#define IDM_VOLUME	576
#define IDM_VOLUME_CALC	577
#define IDM_ZEILENMITTEL                541

#define IDM_POROPERTIES	1
#define IDM_SAVE_AS_BMPSEQ	102
#define IDM_SAVE_MOVIE	101
#define IDM_CORRELATION	584

#define INFO_TEXT                       350

#define I_ASCII                         26
#define I_BMP                           29
#define I_COPY                          23
#define I_DESPIKE                       6
#define I_DI                            27
#define I_GWY							227
#define I_DIFFERENTIAL                  41
#define I_EXPORT                        12
#define I_FFT	79
#define I_FREE_MEMORY                   8
#define I_GLAETTUNG                     18
#define I_GROSS                         7
#define I_HDF                           28
#define I_IMPORT                        10
#define I_INVERT                        19
#define I_KONTUR                        22
#define I_PRINTING                      13
#define I_REDRAW                        9
#define I_SAVE_FILE                     40
#define I_SAVE_WND                      11
#define I_SNOM_HDF	75
#define I_TURN                          20
#define I_UNDO                          14
#define I_WINKEL                        21
#define I_X_DIFF                        15
#define I_DOTS							217
#define I_Y_DIFF                        17
#define I_ZEILENMITTEL                  5

#define MESS_APPROACH_SPANNUNG	111

#define MATHE_AND                       38
#define MATHE_FEST                      219
#define MATHE_GETEILT                   47
#define MATHE_HOCH                      39
#define MATHE_LOG                       108
#define MATHE_MAL                       42
#define MATHE_MINUS                     45
#define MATHE_MODULO                    37
#define MATHE_OR                        124
#define MATHE_OVERFLOW                  222
#define MATHE_PLUS                      43
#define MATHE_QUELLE                    221
#define MATHE_WERT                      220
#define MATHE_XOR                       94

#define MEDIAN_2X2                      116
#define MEDIAN_3X3                      117
#define MEDIAN_3ZEILEN                  113
#define MEDIAN_5X5                      118
#define MEDIAN_5ZEILEN                  114
#define MEDIAN_7ZEILEN                  115

#define MESS_ABORT	108
#define MESS_BITMAP	758
#define MESS_FREQ_AMPLITUDE	104
#define MESS_FREQ_MITTE	102
#define MESS_FREQ_PHASE	111
#define MESS_FREQ_WEITE	103
#define MESS_GROB_POS                   107
#define MESS_GROB_SCROLL                106
#define MESS_GROB_SETZEN                108
#define MESS_HOEHE	131
#define MESS_MESS_MODUS	120
#define MESS_NOT_SQUARE	113
#define MESS_OSZI                       555
#define MESS_PID_VOLTAGE	114
#define MESS_PID_SPS	115
#define IDM_SCAN_FOREVER	114
#define MESS_PID_DIFF                   104
#define MESS_PID_FREQ                   105
#define MESS_PID_INT                    103
#define MESS_PID_PROP                   102
#define MESS_PID_SEND	113
#define MESS_PID_SHOW_SOLL              106
#define MESS_PID_SOLL                   107
#define MESS_PIEZO_X	112
#define MESS_PIEZO_Y	110
#define MESS_PIEZO_Z	111
#define MESS_RESCALE			122
#define MESS_SAVE	112
#define MESS_SCAN_FREQ                  123
#define MESS_SCAN_INVERT	109
#define MESS_SCAN_SEND	127
#define MESS_SCAN_FOREVER	190
#define MESS_SCAN_SIZE	128
#define MESS_SCAN_VERSATZ               124
#define MESS_SCAN_XPTS                  125
#define MESS_SCAN_YPTS			121
#define MESS_SER_PAR	102
#define MESS_SER_PORT	101
#define MESS_SER_TERMINAL	103
#define MESS_SKALA	759
#define MESS_WEITE	130
#define MESS_WHICH_WAY			126
#define MESS_XOFF	132
#define MESS_X_SCROLL                   115
#define MESS_YOFF	133
#define MESS_Y_SCROLL                   106
#define MESS_ZURUECK                    198
#define MESS_SP_IST	178
#define MESS_PROZENT	182
#define MESS_SCAN_INVERT	109
#define MESS_EXPONENTIALLY	134
#define MESS_PID_COARSEAPPROACH 135
#define MESS_APPROACH_PORT	101
#define MESS_APPROACH_ZSCANNER	181
#define MESS_APPROACH_ZSCANNER1	191
#define MESS_APPROACH_AUTO_DIALOG	183
#define MESS_APPROACH_AUTO_APPROACH	184
#define MESS_APPROACH_AUTO_STOP	189
#define MESS_APPROACH_AUTO_CANCEL	185
#define MESS_APPROACH_AUTO_FAST	186
#define MESS_APPROACH_AUTO_SLOW	187
#define MESS_APPROACH_AUTO_STANDARD	188
#define MESS_APPROACH_PULSDAUER	110
#define MESS_APPROACH_ANZPULSE	109
#define MESS_APPROACH_APPROACH	222
#define MESS_APPROACH_RETRACT	333
#define MESS_APPROACH_STOP	115
#define MESS_APPROACH_TASTSTOP	114
#define MESS_APPROACH_TASTDRIVE	113

#define MITTEL3D_HORIZONTAL             109
#define MITTEL3D_KONST                  106
#define MITTEL3D_LIN                    107
#define MITTEL3D_QUAD                   108
#define MITTEL3D_VERTIKAL               110
#define MITTEL3D_XRASTER                104
#define MITTEL3D_YRASTER                105
#define MITTEL_0                        101
#define MITTEL_1                        102
#define MITTEL_2                        103
#define MITTEL_FIT                      104
#define MITTEL_N                        105
#define MITTEL_ANGLE                    111
#define MITTEL_ROTATE                   112

#define OVERRUN_OVERFLOW                102
#define OVERRUN_UNDERFLOW               103

#define OVER_DIR	10
#define OVER_DATE	11
#define OVER_NUMBER	12
#define OVER_NAME	13
#define OVER_LIST	14
#define OVER_CHANGE_DIR	15
#define OVER_INVERT	16
#define OVER_SMOOTH	17
#define OVER_FLATTEN	18
#define OVER_FLATTEN_LINE	18
#define OVER_FLATTEN_3D	19

#define PROFIL_AMPLITUDE                118
#define PROFIL_AUTOKORRELATION          116
#define PROFIL_DISTANZ                  113
#define PROFIL_WERTE                    117
#define PROFIL_X                        114
#define PROFIL_Y                        115

#define PROG_EVAL_ASSIGN	57
#define PROG_EVAL_CHAR	54
#define PROG_EVAL_OPERATOR	56
#define PROG_EVAL_STRING	50
#define PROG_EVAL_TYPES	55
#define PROG_LINE_OVERFLOW	44
#define PROG_OK	78
#define PROG_OP_ILLEGAL	59
#define PROG_PARSE_BRACKETS	53
#define PROG_PARSE_EOL	49
#define PROG_PARSE_STACK_OVER	52
#define PROG_PARSE_STACK_UNDER	51
#define PROG_PARSE_WRONG	58
#define PROG_VAR_NULLNAME	46
#define PROG_VAR_OUT_OF_NAMES	47
#define PROG_VAR_SUBTYPE	45
#define PROG_VAR_UNDEF	48

#define ROH_10BIT                       110
#define ROH_12BIT                       112
#define ROH_16BIT                       116
#define ROH_8BIT                        108
#define ROH_HOEHE                       103
#define ROH_INTEL                       104
#define ROH_OFFSET                      101
#define ROH_UNSIGNED	117
#define ROH_WEITE                       102

#define SCANBARBMP                      128
#define SCAN_RESTART	114

#define SPIKE_INTERPOL                  107
#define SPIKE_LOW                       104
#define SPIKE_LOW_OK                    103
#define SPIKE_UP                        106
#define SPIKE_UP_OK                     105
#define SPIKE_WECHSELE	7878
#define SPIKE_WEITE                     108
#define SPIKE_X                         101
#define SPIKE_Y                         102

#define STR_ANGLE_PLOT	69
#define STR_CONTUR_PLOT	70
#define STR_ENDE_PID	62
#define STR_FRAC_LINE	76
#define STR_FRAC_RECT	77
#define STR_HOEHENLINIEN	71
#define STR_LUMI_MEAN	67
#define STR_MASK	74
#define STR_NEW_F	65
#define STR_NOT_SEND	63
#define STR_ORIENT	68
#define STR_PART_OF	72
#define STR_REGEL	60
#define STR_SCANLINE	73
#define STR_SCANNING	64
#define STR_TOPO_MEAN	66
#define STR_VOLUME 179
#define STR_VOLUME_MARK 180

#define TOOLBARBMP                      127

#define VOLUME_RECALC	222
#define VOLUME_RESULT	204
#define VOLUME_TOLERANCE	208
#define WINKEL_LOGARITHMUS              102

#define W_COMMENT                       31
#define W_NIX                           4
#define W_OVERFLOW                      2
#define W_STATISTIK                     16

#define QD_SCROLL_TOLERANCE 500
#define QD_EDIT_TOLERANCE 501
#define QD_CENTER_ON_DOT 502
#define QD_REMOVE_ASSYMETRIC 503
#define QD_EDIT_ASSYMETRIC 504
#define QD_REMOVE_TOO_HIGH 505
#define QD_EDIT_TOO_HIGH 506
#define QD_REMOVE_OVERLAP 507
#define QD_EDIT_OVERLAP 508
#define QD_RADIUS 509
#define QD_EDIT_RADIUS 510
#define QD_RESULT 511

//
#if !defined(SS_BITMAP)
#define SS_BITMAP           0x0000000EL
#endif

